# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab9winter2019part2I2CuartIP.xdc

# Block Designs: bd/lab9winter2019part2I2CuartIP/lab9winter2019part2I2CuartIP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP || ORIG_REF_NAME==lab9winter2019part2I2CuartIP}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_processing_system7_0_0/lab9winter2019part2I2CuartIP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_processing_system7_0_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_processing_system7_0_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_0_0/lab9winter2019part2I2CuartIP_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_0_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_0_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_processing_system7_0_axi_periph_0/lab9winter2019part2I2CuartIP_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_processing_system7_0_axi_periph_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_UARTmodule2019_0_1/lab9winter2019part2I2CuartIP_UARTmodule2019_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_UARTmodule2019_0_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_UARTmodule2019_0_1}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_xbar_0/lab9winter2019part2I2CuartIP_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_xbar_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_xbar_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_2/lab9winter2019part2I2CuartIP_axi_gpio_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_2 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_2}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_1/lab9winter2019part2I2CuartIP_axi_gpio_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_1}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_0/lab9winter2019part2I2CuartIP_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_0/lab9winter2019part2I2CuartIP_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_0/lab9winter2019part2I2CuartIP_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_0/lab9winter2019part2I2CuartIP_axi_gpio_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_pwmGenerator_0_0/lab9winter2019part2I2CuartIP_pwmGenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_pwmGenerator_0_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_pwmGenerator_0_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_pwmGenerator_0_1/lab9winter2019part2I2CuartIP_pwmGenerator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_pwmGenerator_0_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_pwmGenerator_0_1}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_1/lab9winter2019part2I2CuartIP_axi_gpio_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_1}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_1/lab9winter2019part2I2CuartIP_axi_gpio_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_1}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_pwmGenerator_1_0/lab9winter2019part2I2CuartIP_pwmGenerator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_pwmGenerator_1_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_pwmGenerator_1_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_7_0/lab9winter2019part2I2CuartIP_axi_gpio_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_7_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_7_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_8_0/lab9winter2019part2I2CuartIP_axi_gpio_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_8_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_8_0}]

# IP: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_auto_pc_0/lab9winter2019part2I2CuartIP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_auto_pc_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_auto_pc_0}]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_processing_system7_0_0/lab9winter2019part2I2CuartIP_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_processing_system7_0_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_0_0/lab9winter2019part2I2CuartIP_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_0_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_0_0/lab9winter2019part2I2CuartIP_axi_gpio_0_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_0_0/lab9winter2019part2I2CuartIP_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_0_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0}]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0}]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0/lab9winter2019part2I2CuartIP_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_xbar_0/lab9winter2019part2I2CuartIP_xbar_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_2/lab9winter2019part2I2CuartIP_axi_gpio_1_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_2 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_2}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_2/lab9winter2019part2I2CuartIP_axi_gpio_1_2_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_2/lab9winter2019part2I2CuartIP_axi_gpio_1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_2 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_2}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_1/lab9winter2019part2I2CuartIP_axi_gpio_2_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_1/lab9winter2019part2I2CuartIP_axi_gpio_2_1_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_1/lab9winter2019part2I2CuartIP_axi_gpio_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_0/lab9winter2019part2I2CuartIP_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_0/lab9winter2019part2I2CuartIP_axi_gpio_1_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_1_0/lab9winter2019part2I2CuartIP_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_0/lab9winter2019part2I2CuartIP_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_0/lab9winter2019part2I2CuartIP_axi_gpio_2_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_2_0/lab9winter2019part2I2CuartIP_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_0/lab9winter2019part2I2CuartIP_axi_gpio_5_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_0/lab9winter2019part2I2CuartIP_axi_gpio_5_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_0/lab9winter2019part2I2CuartIP_axi_gpio_5_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_0/lab9winter2019part2I2CuartIP_axi_gpio_6_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_0/lab9winter2019part2I2CuartIP_axi_gpio_6_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_0/lab9winter2019part2I2CuartIP_axi_gpio_6_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_1/lab9winter2019part2I2CuartIP_axi_gpio_5_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_1}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_1/lab9winter2019part2I2CuartIP_axi_gpio_5_1_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_5_1/lab9winter2019part2I2CuartIP_axi_gpio_5_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_5_1}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_1/lab9winter2019part2I2CuartIP_axi_gpio_6_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_1}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_1/lab9winter2019part2I2CuartIP_axi_gpio_6_1_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_6_1/lab9winter2019part2I2CuartIP_axi_gpio_6_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_1 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_6_1}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_7_0/lab9winter2019part2I2CuartIP_axi_gpio_7_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_7_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_7_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_7_0/lab9winter2019part2I2CuartIP_axi_gpio_7_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_7_0/lab9winter2019part2I2CuartIP_axi_gpio_7_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_7_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_7_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_8_0/lab9winter2019part2I2CuartIP_axi_gpio_8_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_8_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_8_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_8_0/lab9winter2019part2I2CuartIP_axi_gpio_8_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_axi_gpio_8_0/lab9winter2019part2I2CuartIP_axi_gpio_8_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_8_0 || ORIG_REF_NAME==lab9winter2019part2I2CuartIP_axi_gpio_8_0}] {/U0 }]/U0 ]]

# XDC: bd/lab9winter2019part2I2CuartIP/ip/lab9winter2019part2I2CuartIP_auto_pc_0/lab9winter2019part2I2CuartIP_auto_pc_0_ooc.xdc

# XDC: bd/lab9winter2019part2I2CuartIP/lab9winter2019part2I2CuartIP_ooc.xdc
